modLoader="kotlinforforge"
loaderVersion="[1,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/thebrightspark/Land-Manager/issues"

[[mods]]
    modId="lmr"
    version="${version}"
    displayName="Land Manager Reloaded"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/land-manager"
    #logoFile="banner.png"
    authors="_Octave, bright_spark,"
    description='''
    Manage custom sized areas of the world and allocate them to players!
    '''

[[dependencies.lmr]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

